### ISSUE TITLE
Container Orchestration :  "error: You must be logged in to the server (the server has asked for the client to provide credentials)" from kubectl get nodes command

### ISSUE THREAD

**Issue by LingfeiXie** [LingfeiXie/Snap-Pelion-Edge-Test#2]
I have built pelion-edge_1.18.1_amd64.snap and run it on Ubuntu 18.04(LTS)

Here shows the active services

```
services:
pelion-edge.devicedb: simple, disabled, inactive
pelion-edge.dockerd: simple, enabled, active
pelion-edge.edge-core: simple, enabled, active
pelion-edge.edge-proxy: simple, enabled, active
pelion-edge.identity: simple, enabled, inactive
pelion-edge.kubelet: simple, enabled, active
pelion-edge.maestro: simple, enabled, active
pelion-edge.relay-term: simple, enabled, active
```
I generated a kubeconfig file with the template and pasted my  API-Key.

```
apiVersion: v1
clusters:
- cluster:
    server: https://edge-k8s.us-east-1.mbedcloud.com
  name: edge-k8s
contexts:
- context:
    cluster: edge-k8s
    user: edge-k8s
  name: edge-k8s
current-context: edge-k8s
kind: Config
preferences: {}
users:
- name: edge-k8s
  user:
    token: YOUR API KEY HERE
```
But when i try to list nodes, kubectl gives the following error:
```
error: You must be logged in to the server (the server has asked for the client to provide credentials)
```
It also happens with the command $kubectl version
```
(build-venv) denso@MB-B509:~/build-venv$ kubectl version
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.3", GitCommit:"5e53fd6bc17c0dec8434817e69b04a25d8ae0ff0", GitTreeState:"clean", BuildDate:"2019-06-06T01:44:30Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
error: You must be logged in to the server (the server has asked for the client to provide credentials)
```
 
Is there something i miss? Thanks in advance.
